# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    branches:
      ignore:
        - do-not-execute_autotests
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/Auto-Lvl-2---Add-integration-with-CircleCI-devOps-/Web-Test-Project

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout:
          path: ~/Auto-Lvl-2---Add-integration-with-CircleCI-devOps-

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-        
            
      - run: chmod +x ./gradlew && ./gradlew dependencies
      
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-dependencies-{{ checksum "build.gradle" }}

      #- run: gradle dependencies
      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: ./gradlew -i test -Dbrowser=ff
      
      - store_test_results:
          path: build/test-results/test
          
      - store_artifacts:
          path: build/reports/tests/test
          destination: circleci-docs

  job2:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    working_directory: ~/Auto-Lvl-2---Add-integration-with-CircleCI-devOps-/Web-Test-Project

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout:
          path: ~/Auto-Lvl-2---Add-integration-with-CircleCI-devOps-

      - restore_cache:
          keys:
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
            
      - run: chmod +x ./gradlew && ./gradlew dependencies
      
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-dependencies-{{ checksum "build.gradle" }}
          
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew -v